name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: luisfeser/photo-video-organizer:latest
        platforms: linux/amd64,linux/arm/v7,linux/arm64

    - name: Verify Docker Hub upload
      run: docker run --rm luisfeser/photo-video-organizer:latest echo "Docker image built and uploaded successfully"
